# **Machine Learning Model steps**


1. Import all libraries like numpy,pandas,tensor/keras, sklearn
2. Import Data using pandas, pd.read_csv
3. EDA or prepocessing like encoding, transforming
4. Data Cleaning
5. Make target variables x and y then divide data into two parts:- training , testing using train_test_split in ratio 8:2 o 7:3
6. Import ML model
7. Fit training data into model using model.fit()
8. Predict using the data using .predict function:- model.predict(data)
9. Check the evaluation:- R2 score,F1 score, accuracy
10. Convert model into pkl file
11. Making the GUI.
12. Pkl file adjusts into GUI code.

In [20]:
import pandas as pd, numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import pickle

# *Importing and Cleaning the Data*

In [7]:
df=pd.read_csv("/content/salary_data.csv")
df.head()
print(df.isnull().sum())

YearsExperience    0
Salary             0
dtype: int64

In [15]:
X= df[['YearsExperience']]
y=df['Salary']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# **Importing the ML Model and predicting the salary**

In [18]:
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)

R2=r2_score(y_test,y_pred)
print(R2)

0.9024461774180497

In [23]:
y_pred=pd.DataFrame(y_pred)
y_pred.head()

               0
0  115790.210113
1   71498.278095
2  102596.868661
3   75267.804224
4   55477.792045

In [22]:
y_test

27    112635.0
15     67938.0
23    113812.0
17     83088.0
8      64445.0
9      57189.0
Name: Salary, dtype: float64