## **Pandas Continuity**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/Salary_Dataset_DataScienceLovers.csv")
df.head()

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles
0,3.8,Sasken,Android Developer,400000,3,Bangalore,Full Time,Android
1,4.5,Advanced Millennium Technologies,Android Developer,400000,3,Bangalore,Full Time,Android
2,4.0,Unacademy,Android Developer,1000000,3,Bangalore,Full Time,Android
3,3.8,SnapBizz Cloudtech,Android Developer,300000,3,Bangalore,Full Time,Android
4,4.4,Appoids Tech Solutions,Android Developer,600000,3,Bangalore,Full Time,Android

In [ ]:
df.tail()

,Rating,Company Name,Job Title,Salary,Salaries Reported,Location,Employment Status,Job Roles
22765,4.7,Expert Solutions,Web Developer,200000,1,Bangalore,Full Time,Web
22766,4.0,Nextgen Innovation Labs,Web Developer,300000,1,Bangalore,Full Time,Web
22767,4.1,Fresher,Full Stack Web Developer,192000,13,Bangalore,Full Time,Web
22768,4.1,Accenture,Full Stack Web Developer,300000,7,Bangalore,Full Time,Web
22769,3.8,Thomson Reuters,Associate Web Developer,300000,7,Bangalore,Full Time,Web

In [ ]:
df.info()
print(df.isnull().sum())
print(df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22770 entries, 0 to 22769
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rating             22770 non-null  float64
 1   Company Name       22769 non-null  object
 2   Job Title          22770 non-null  object
 3   Salary             22770 non-null  int64
 4   Salaries Reported  22770 non-null  int64
 5   Location           22770 non-null  object
 6   Employment Status  22770 non-null  object
 7   Job Roles          22770 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.4+ MB
Rating               0
Company Name         1
Job Title            0
Salary               0
Salaries Reported    0
Location             0
Employment Status    0
Job Roles            0
dtype: int64
0

In [ ]:
df.describe()

             Rating        Salary  Salaries Reported
count  22770.000000  2.277000e+04       22770.000000
mean       3.918213  6.953872e+05           1.855775
std        0.519675  8.843990e+05           6.823668
min        1.000000  2.112000e+03           1.000000
25%        3.700000  3.000000e+05           1.000000
50%        3.900000  5.000000e+05           1.000000
75%        4.200000  9.000000e+05           1.000000
max        5.000000  9.000000e+07         361.000000

In [ ]:
new_df=df.dropna()
new_df.isnull().sum()
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22769 entries, 0 to 22769
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rating             22769 non-null  float64
 1   Company Name       22769 non-null  object
 2   Job Title          22769 non-null  object
 3   Salary             22769 non-null  int64
 4   Salaries Reported  22769 non-null  int64
 5   Location           22769 non-null  object
 6   Employment Status  22769 non-null  object
 7   Job Roles          22769 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.6+ MB